# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Repyy < Formula
  desc "Scan unfamiliar source repositories before running their code"
  homepage "https://github.com/Kevin-Umali/repyy"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Kevin-Umali/repyy/releases/download/v0.3.1/repyy_0.3.1_darwin_amd64.tar.gz"
      sha256 "2c40f5a9fbdc5ccc56c7353e032f0cd0ac3a5f1f0c597ec9da312c7315510216"

      define_method(:install) do
        bin.install "repyy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Kevin-Umali/repyy/releases/download/v0.3.1/repyy_0.3.1_darwin_arm64.tar.gz"
      sha256 "f1b816bd0cc71d547434b6cc75792c4860ca8bb4c245a6eeb5d4c6b6908c71fe"

      define_method(:install) do
        bin.install "repyy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kevin-Umali/repyy/releases/download/v0.3.1/repyy_0.3.1_linux_amd64.tar.gz"
      sha256 "55e0b12bac112dd05a7b95b976c32eba325aa65a96e50acfaaf36335a2a39746"
      define_method(:install) do
        bin.install "repyy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kevin-Umali/repyy/releases/download/v0.3.1/repyy_0.3.1_linux_arm64.tar.gz"
      sha256 "21e4c33b85afd56f9ed311dff74b36d3005a765a6730e6760836f18b959af93a"
      define_method(:install) do
        bin.install "repyy"
      end
    end
  end

  test do
    system "#{bin}/repyy", "version"
  end
end
