# This file was generated by GoReleaser. DO NOT EDIT.
cask "repyy" do
  version "0.5.1"

  on_macos do
    on_arm do
      sha256 "66ef8dd48fe0b027ef975f81712b2ffaf6b9a5c79e26ff00da0e340d46617539"
      url "https://github.com/Kevin-Umali/repyy/releases/download/v#{version}/repyy_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4b0ea0a8e21d9b27a835b53d28f3a7a6d722f4a0b2b555be2f2062fc72ed8bd4"
      url "https://github.com/Kevin-Umali/repyy/releases/download/v#{version}/repyy_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d513ee917993cc558d4304a521a99060a14ac8234a46543dbaf18949b58defa6"
      url "https://github.com/Kevin-Umali/repyy/releases/download/v#{version}/repyy_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "eacb36306d6a22bab37eadda52f1af5b597a49ec91f524f13ee7e9ecd64f30a6"
      url "https://github.com/Kevin-Umali/repyy/releases/download/v#{version}/repyy_#{version}_linux_amd64.tar.gz"
    end
  end

  name "repyy"
  desc "Scan unfamiliar source repositories before running their code"
  homepage "https://github.com/Kevin-Umali/repyy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repyy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/repyy"]
    end
  end

  # No zap stanza required
end
