# This file was generated by GoReleaser. DO NOT EDIT.
cask "repyy" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "8441c9b5bf7f2ac0edc9ae80aee4d970d2c93b390237cf974fafbee625443f80"
      url "https://github.com/Kevin-Umali/repyy/releases/download/v#{version}/repyy_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "721f74e3f6275ffaa9bd1227005924d6bf084b42cf39a62bbd0d61065f9703c9"
      url "https://github.com/Kevin-Umali/repyy/releases/download/v#{version}/repyy_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "482c5a2eb843cc940855d40fca1be123eb9485b9d125e5062d4cc56572eba551"
      url "https://github.com/Kevin-Umali/repyy/releases/download/v#{version}/repyy_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5a58d8c30e0c29fb787139e856e0e1259ba7893db029ad72e821795b58f8df79"
      url "https://github.com/Kevin-Umali/repyy/releases/download/v#{version}/repyy_#{version}_linux_amd64.tar.gz"
    end
  end

  name "repyy"
  desc "Scan unfamiliar source repositories before running their code"
  homepage "https://github.com/Kevin-Umali/repyy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repyy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/repyy"]
    end
  end

  # No zap stanza required
end
