# This file was generated by GoReleaser. DO NOT EDIT.
cask "repyy" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "9808b99bdf591b2fb8e70264e0005be7f10e3a431c7f5349a82347499b1a3d44"
      url "https://github.com/Kevin-Umali/repyy/releases/download/v#{version}/repyy_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "885f5fcc5b671810749181643a5e7bafa3a2ab1ec34d84cf2ff0dd89da807ef1"
      url "https://github.com/Kevin-Umali/repyy/releases/download/v#{version}/repyy_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "bd11c737420960af75c798437edd1940d465381989c7e7141becd6d7bbdc7c55"
      url "https://github.com/Kevin-Umali/repyy/releases/download/v#{version}/repyy_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "684f912070006a113045647a85d54fc03f3b447dbb938435d662fb11d1008368"
      url "https://github.com/Kevin-Umali/repyy/releases/download/v#{version}/repyy_#{version}_linux_amd64.tar.gz"
    end
  end

  name "repyy"
  desc "Scan unfamiliar source repositories before running their code"
  homepage "https://github.com/Kevin-Umali/repyy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repyy"

  # No zap stanza required
end
